### ISSUE TITLE
[chore] 배포 자동화를 위한 fastlane 세팅

### ISSUE THREAD

**Issue by dayo2n** [DeveloperAcademy-POSTECH/MC3-Team15-RockStars#108]
#  Description
취업공고보다가 사용 툴에서 fastlane을 발견해서 보니 스크린샷, 프로비저닝 프로파일, 배포과정 (아카이빙, 배포 등)의 과정을 자동화해주는 아이더라구요 알고보니까 진작에 알아서 적용했으면 좋았을 걸 싶네요 ㅎ
간단한건 아니고 다같이 세팅이 필요한거라 제의 겸 올립니다 ~.~
```
fastlane is a tool for iOS and Android developers to automate tedious tasks 
like generating screenshots, dealing with provisioning profiles, and releasing your application.
```
[참고하면 좋은 링크](https://medium.com/hcleedev/ios-%EB%B0%B0%ED%8F%AC-%EC%9E%90%EB%8F%99%ED%99%94-fastlane-%EC%8B%9C%EC%9E%91%EB%B6%80%ED%84%B0-%EC%A0%81%EC%9A%A9%EA%B9%8C%EC%A7%80-3d9107cdc3b4)

# TODO
- [x] fastlane 쓸까요?
- [x] fastlane 세팅!

**Comment by jaelyung** [comment]
배포 자동화 굿인데요!! 적용해보면 너무 좋을것같아요👍👍

**Comment by Damagucci-Juice** [comment]
좋아요!

**Comment by dayo2n** [comment]
<img width="697" alt="스크린샷 2023-08-15 오후 2 32 54" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/57654681/ab9fd0ed-7257-42f4-b299-9dfeddbc31a2">

**Comment by dayo2n** [comment]
<img width="935" alt="스크린샷 2023-08-15 오후 2 58 18" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/57654681/03c64762-e3d9-4747-8d65-8384c38dc04e">
