### ISSUE TITLE
[fix] 위험상황 배경이 시작될 때 잘리는 현상

### ISSUE THREAD

**Issue by dayo2n** [DeveloperAcademy-POSTECH/MC3-Team15-RockStars#14]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

# Description
#6 에서 넘어왔습니다
정상 주행 상태에서 급감가속이 감지되어 위험상황으로 뷰가 전환될 때, 백그라운드가 잘린듯한 이미지가 보입니다... 왼쪽을 주목~!
<img src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/57654681/8e036cd4-49bb-4b07-993e-122562940d51" width="270">

# TODO
- [ ] redSky 배경이미지 시작할 때 화면 width만큼 반복되는 원인찾기
- [ ] 해결하기

**Comment by pppineappple** [comment]
지금 사진으로 보이는 걸로 다시 확인할 땐 이미지 문제일 수도 있겠네요 .. 바뀐 이미지로 한 번 적용해보시면 문제가 해결될 거 같아요!

**Comment by dayo2n** [comment]
에셋바뀌면서 해결 예정
