### ISSUE TITLE
[refactor] LiveActivityModel에 싱글톤 패턴을 적용합니다 

### ISSUE THREAD

**Issue by dayo2n** [DeveloperAcademy-POSTECH/MC3-Team15-RockStars#33]
#  Description
EnvironmentObject로 모든 곳에서 LiveActivityModel의 프로퍼티와 함수를 사용하고 있는데, 
객체를 단 하나만 사용해야 하기 때문에 인스턴스를 담은 shared를 선언하고 이 놈을 통해 접근하도록 합니다
```swift
final class LiveActivityModel: ObservableObject, DriveSimulatorDelegate {
    static let shared = LiveActivityModel()
// 중략
```

# TODO
- [ ] 인스턴스를 담은 shared를 선언하고 이를 통해 접근하도록 수정합니다

**Comment by Damagucci-Juice** [comment]
적용된 이슈니까 클로즈 할게요.
