### ISSUE TITLE
[fix] 급감가속이 될 때 애니메이션이 씹히는 경우

### ISSUE THREAD

**Issue by dayo2n** [DeveloperAcademy-POSTECH/MC3-Team15-RockStars#35]
# Description
급 감가속은 감지되어서 카운팅은 되는데 애니메이션은 안됨

# TODO
- [ ] 디버깅 - 원인파악 (애니메이션을 위해 모션을 업데이트해오는 위치에서 쓰레드를 5초 재우는 부분에 문제가 있을까?)
- [ ] 버튼 동작 수정!

**Comment by dayo2n** [comment]
close with #37

**Comment by Damagucci-Juice** [comment]
이 문제 지금도 있는 문제인가요?

**Comment by dayo2n** [comment]
아 이거 아마 연속으로 함수 불렀던 문제같은데 정확히 기억 안나네요 닫아둘게요~~ 늦게봐써여
