### ISSUE TITLE
[refactor] 다이나믹아일랜드 DrivePalWidgetExtension 리팩토링

### ISSUE THREAD

**Issue by jaelyung** [DeveloperAcademy-POSTECH/MC3-Team15-RockStars#57]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

#  Description
개발하려는 기능은 이런 거예요
LiveActivity 에서 Expanded Appearance로 View 파일 4개를 하나로 합치고 싶어요.
[View 폴더](https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/tree/c184219534d24682637d5b854c0eb604d2b7422c/DrivePalWidgetExtension/View)

[AfterFourWarningsView.swift](https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/blob/develop/DrivePalWidgetExtension/View/AfterFourWarningsView.swift)
[NormalDrivingView.swift](https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/blob/develop/DrivePalWidgetExtension/View/NormalDrivingView.swift)
[SuddenAccelerationView.swift](https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/blob/develop/DrivePalWidgetExtension/View/SuddenAccelerationView.swift)
[SuddenStopView.swift](https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/blob/develop/DrivePalWidgetExtension/View/SuddenStopView.swift)

![image](https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/61307199/466d32d0-a37a-4b37-9587-dd4705e058fa)

![image](https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/61307199/e22d82dc-693c-4691-8c63-75de42da8c48)

# TODO
- [x] Expanded View 4개 -> 1개로 리팩토링

**Comment by jaelyung** [comment]
`//
//  ExpandedView.swift
//  DrivePalWidgetExtension
//
//  Created by jaelyung kim on 2023/07/25.
//

import SwiftUI


struct ExpandedView: View {
    @State var expandedImageName: String
    @State var progress: Double
    @State var count: Int
    @State var timestamp: Int
    @State var motionStatue: MotionStatus
    
    // TODO: 제나 코드 머지하면 MotionStatus 받아와서 적용할 부분입니다
    enum MotionStatus {
        case normal, suddenAcceleration, suddenStop, afterFourWarning
    }
    let motionStatus: MotionStatus
    
    var body: some View {
        ZStack {
            HStack(alignment: VerticalAlignment.top) {
                Image("\(expandedImageName)")
                    .resizable()
                    .frame(width: 54, height: 53)
                    .padding(.trailing, 5)
                VStack(alignment: .leading) {
                    Text(motionStatusDescription)
                        .font(.system(size: 20, weight: .semibold))
                    HStack {
                        Image(locationPinImage)
                            .resizable()
                            .frame(width: 8, height: 10)
                        Text("포항시 효성로 13번길 2")
                            .font(.system(size: 10))
                    }
                    .padding(.bottom, 17)
                    HStack {
                        Text("경고")
                            .font(.system(size: 8))
                            .opacity(textOpacity)
                        Text(countDescription)
                            .font(.system(size: 15, weight: .bold))
                            .foregroundColor(warningColor)
                        
                        Spacer()
                        
                        Text("운전시간")
                            .font(.system(size: 8))
                            .opacity(textOpacity)
                        Text("\(timestamp / 60) min")
                            .font(.system(size: 15, weight: .bold))
                            .opacity(textOpacity)
                    }
                    .frame(width: UIScreen.width / 2.7)
                }
                Spacer()
            }
            .padding(.leading, 40)
            LinearProgressView(progress: progress < 1.0 ? progress : 1.0, linearColor: linearColor)
                .frame(width: 256)
                .offset(y: 17)
        }
    }
    
    var motionStatusDescription: String {
        if motionStatus == .normal {
            return "운전중...🛫슈욱~"
        } else if motionStatus == .suddenAcceleration {
            return "급가속 주의 속도 🎢 낮춰~"
        } else if motionStatus == .suddenStop {
            return "급감속 주의 📉 위험!"
        } else {
            return "나쁜 운전중 🤬 #$%"
        }
    }
    
    var locationPinImage: String {
        if motionStatus == .normal {
            return "locationPinBlue"
        } else if motionStatus == .suddenAcceleration {
            return "locationPinPink"
        } else if motionStatus == .suddenStop {
            return "locationPinYellow"
        } else {
            return "locationPinRed"
        }
    }
    
    var countDescription: String {
        if motionStatus == .suddenAcceleration || motionStatus == .suddenStop {
            return "+ 1번"
        } else {
            return "\(count.description)번"
        }
    }
    
    var textOpacity: Double {
        if motionStatus == .normal {
            return 0.4
        } else if motionStatus == .suddenAcceleration || motionStatus == .suddenStop {
            return 1.0
        } else {
            return 0.8
        }
    }
    
    var warningColor: Color {
        if motionStatus == .normal {
            return Color(hex: "0EF1FF")
        } else if motionStatus == .suddenAcceleration {
            return Color(hex: "FF26A8")
        } else if motionStatus == .suddenStop {
            return Color(hex: "DFFF1C")
        } else {
            return Color(hex: "FF5050")
        }
    }
    
    var linearColor: String {
        if motionStatus == .normal {
            return "0EF1FF"
        } else if motionStatus == .suddenAcceleration {
            return "FF26A8"
        } else if motionStatus == .suddenStop {
            return "DFFF1C"
        } else {
            return "FF5050"
        }
    }
}
`

**Comment by dayo2n** [comment]
어서오세요 영 🤗❤️

**Comment by Damagucci-Juice** [comment]
![image](https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/50472122/38308fac-5edb-435e-aeac-3a08959c528a)
