### ISSUE TITLE
[fix] 로컬라이징 이후 화면 비율 깨짐 및 현지화 덜된 부분 수정 

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MC3-Team15-RockStars#64]
# Description
| 화면에 딱 붙음 | 일부 로컬라이징 안됨 |
| ------ | ------ |
| ![IMG_2136](https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/50472122/4beb6382-a401-4681-9687-2acce16aa926) | ![IMG_2137](https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/50472122/006b7139-6091-41a2-9cc5-10aee330c30f) |

# TODO
- [ ] `OnBoardingView` padding 값 주기
- [ ] `ResultView`에서 사용하는 글자를 localization 파일에 추가하기

**Comment by dayo2n** [comment]
온보딩이랑 결과창 디자인 바뀔거라!
결과창은 #68에서 해결할게요
