### ISSUE TITLE
[fix] 결과 분석창 화면 안뜸

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MC3-Team15-RockStars#77]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

# Description, exit 버튼을 눌렀을 때

![IMG_180A21C9E3D2-1](https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/50472122/427bdbd5-61bd-4826-b71b-8a5b262aacf3)

# TODO
- [ ] 제냐, 잰나 부탁해요

**Comment by dayo2n** [comment]
버그 아님! 작업안된겁니다 ㅎ 여기 디자인 빡세서 엄두가 안나네여

**Comment by dayo2n** [comment]
close with #79
