### ISSUE TITLE
[docs] gitignore 수정

### ISSUE THREAD

**Issue by dayo2n** [DeveloperAcademy-POSTECH/MC3-Team15-RockStars#8]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

#  Description
레포와 프로젝트 루트 경로가 일치하지 않아서 gitignore가 제대로 적용되지 않는 것들이 있네요 .. 
혹시 몰라서 이슈만 발생하고 내일 공유 후에 수정해서 디벨롭 브랜치에 반영하도록 하겠습니다!
번거롭게 해드려 제송 😭😭

# TODO
- [x] ~~gitignore 수정하기: 프로젝트 루트로부터 추적하도록~~ → .gitignore를 프로젝트 루트로 옮기거나 삭제해서 한 단계 꺼내기

**Comment by Damagucci-Juice** [comment]
한 뎁스 빼는 것으로 합의
