### ISSUE TITLE
[refactor] 다이나믹아일랜드 온보딩이 작아질 때 완전히 사라지게

### ISSUE THREAD

**Issue by dayo2n** [DeveloperAcademy-POSTECH/MC3-Team15-RockStars#96]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

#  Description
지금은 14 pro만 기준으로 구현이 되어있어서 맥스나 다른 폰으로 보면 온보딩이 takingOff동안 쪼그맣게 위에 계속 남아있음
아예 삭제되도록 해주세요

# TODO
- [ ] description

**Comment by Damagucci-Juice** [comment]
님좀 천잰듯?
