### ISSUE TITLE
[feat] 위치를 다이나믹 아일랜드에 표시 

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MC3-Team15-RockStars#99]
#  Description
- 현재 위치를 업데이트하는 코드를 Simulator에 삽입 후 Location이 업데이트 될 때마다 현재 위치를 보여주게 설정

# TODO
- [ ] address 추가 
- [ ] Simulator에 코드 추가

**Comment by dayo2n** [comment]
identical issue with #45
